export const RANKING_LIST_FAIL = "RANKING_LIST_FAIL";
export const RANKING_LIST_REQUEST = "RANKING_LIST_REQUEST";
export const RANKING_LIST_RESET = "RANKING_LIST_RESET";
export const RANKING_LIST_SUCCESS = "RANKING_LIST_SUCCESS";
